name = "AndrewsModpack"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83044f124fe985a30beb6c55a2b4d4c2e85026011d83807d12e0a7bbd969cb6a"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "/datapacks"
