name = "AndrewsModpack"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d23381019f914f72a0e9c7d2e2ab8b2162b476a2e8e174d5e312e66bf3bcecb6"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "/datapacks"
