name = "AndrewsModpack"
author = "andrew"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b6832b3a5bf5df75b960a183754abe97f871ef4633e662c224dd2694eda8a6e"

[versions]
fabric = "0.19.3"
minecraft = "1.20.1"

[options]
datapack-folder = "/datapacks"
