#Need help? Ask on Discord or Github/Gitlab <3 (ps: it is possible that this file contains nothing it's normal)
#Tue Jul 14 09:07:39 ADT 2026
int.villages.spacing=50
int.villages.separation=40
boolean.villages.enabled_custom_config=true
int.villages.salt=10387312
