[general]
percentage = 5
checkArmor = false
armorFilter = []
[message]
sendMessage = true
messageColor = "RED"
[sound]
playSound = false
soundLocation = "minecraft:block.note_block.pling"
volume = 0.6
