#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jul 13 21:02:32 ADT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=photon_v1.3b.zip
enableShaders=true
