# The configuration file for Log Begone

[logbegone]
# If a log message has one of these phrases, it will be filtered out from logging
phrases = [
    "Ignored non-lowercase namespace:",
    "Unused frames in sprite",
    "KONNICHIWA ZA WARUDO!",
    "Parsing error loading recipe deeperdarker:",
    "Unable to parse animation:",
    "Couldn't parse 'easeınoutsine' expression!",
    "Sound Keyframe found for",
    "[STDERR]:",
    "deeperdarker:warden_backtank",
    "Invalid mod icon for icon source",
    "has a broken icon, loading default icon",
    "Detected setBlock in a far chunk",
    "Parsing error loading recipe inmis:baby_backpack",
    "Invalid or unsupported recipe type 'create:milling'",
    "Parsing error loading recipe cornexpansion:milling/corn_flour",
    "Parsing error loading recipe cornexpansion:milling/cornmeal",
    "Parsing error loading custom advancement inmis:baby_backpack: Expected item to be an item, was unknown string 'inmis:baby_backpack'",
    "Parsing error loading custom advancement supplementaries:recipes/planter_rich: Unknown item id 'farmersdelight:rich_soil'",
    "Shader supplementaries:spherify could not find uniform named GameTime in the specified shader program.",
    "Shader supplementaries:spherify could not find uniform named NoiseSpeed in the specified shader program.",
    "Shader supplementaries:spherify could not find uniform named NoiseScale in the specified shader program.",
    "Shader supplementaries:spherify could not find uniform named Intensity in the specified shader program.",
    "Shader supplementaries:spherify could not find uniform named CameraPos in the specified shader program.",
    "No data fixer registered for bygonenether:netherite_bell",
    "No data fixer registered for crystallized_amber",
    "No data fixer registered for sculk_jaw",
    "Registry 'terraform:boat' was empty after loading",
    "Couldn't parse element loot_tables:shutter:blocks/azure_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/blossom_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/wisteria_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/azalea_quark_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/plum_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/willow_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/pine_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/driftwood_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/maple_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/poise_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/ancient_shutter",
    "Couldn't parse element loot_tables:shutter:blocks/river_shutter",
    "Parsing error loading recipe shutter:palm_shutter",
    "Parsing error loading recipe shutter:cypress_shutter",
    "Parsing error loading recipe shutter:gingerbread_shutter",
    "Parsing error loading recipe shutter:muddy_oak_shutter",
    "Parsing error loading custom advancement shutter:recipes/misc/cypress_shutter: Unknown item id 'goodending:cypress_slab'",
    "Parsing error loading custom advancement shutter:recipes/misc/muddy_oak_shutter: Unknown item id 'goodending:muddy_oak_slab'",
    "Parsing error loading custom advancement shutter:recipes/misc/gingerbread_shutter: Unknown item id 'snowyspirit:gingerbread_frosted'",
    "Parsing error loading custom advancement shutter:recipes/misc/palm_shutter: Unknown item id 'beachparty:palm_slab'",
    "Couldn't parse element loot_tables:unusualfishmod:gameplay/fishing/unusual_catch_river_treasure",
    "Couldn't parse element loot_tables:unusualfishmod:gameplay/fishing/unusual_catch_deep_ocean_treasure",
    "Couldn't parse element loot_tables:unusualfishmod:gameplay/fishing/unusual_catch_underground_treasure",
    "Couldn't parse element loot_tables:unusualfishmod:gameplay/fishing/unusual_catch_deep_lukewarm_ocean_treasure",
    "Couldn't parse element loot_tables:aquaculture:gameplay/fishing/treasure_leech",
    "Couldn't parse element loot_tables:unusualfishmod:gameplay/fishing/unusual_catch_dripstone_caves_treasure",
    "Couldn't parse element loot_tables:aquaculture:gameplay/fishing/treasure_neptunium",
    "Parsing error loading recipe sortilege:knowledge_book"
    ]

# If a log message matches one of these regex patterns, it will be filtered out from logging. EX: 
regex = ["Disconnecting VANILLA connection attempt", "Channels "]