version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 128
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 4.0
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
candlelight = true
universal_ores = true
everycomp = true
tide = true
bountiful = true
doapi = true
brewery = true
ribbits = true
frost = true
bygonenether = true
friendsandfoes = true
copperhopper = true
libraryferret = true
comforts = true
yigd = true
soulcandles = true
phantasm = true
amendments = true
handcrafted = true
herbalbrews = true
diagonalfences = true
bakery = true
advancednetherite = true
graveyard = true
gardens_of_the_dead = true
exposure = true
customportalapi = true
naturalist = true
supplementaries = true
absorber = true
enchanted-vertical-slabs = true
deeperdarker = true
suppsquared = true
chipped = true
sawmill = true
endrem = true
cornexpansion = true
farm_and_charm = true
animal_feeding_trough = true
minecraft = true
philipsruins = true
copperrails = true
sortilege = true
gipples_galore = true
regions_unexplored = true
snifferplus = true
betterarcheology = true
endermanoverhaul = true
beautify = true
creeperoverhaul = true
crittersandcompanions = true
netherdepthsupgrade = true
meadow = true
bushierflowers = true
hearth_and_home = true
