# Don't change this! Version used to track needed updates.
version = 0
foxTamingItems = [
    "minecraft:glow_berries"
]
foxBreedingItems = [
    "minecraft:sweet_berries"
]
itemsRestrictedToPick = [  ]
foxesAttackWithOwner = false
foxesTameDirectly = true
foxesTamingChance = 0.35
foxesCanIgnoreMobGriefingRule = true
foxesTrustOnBorn = true
untamedFoxesCanBeTempted = false
untamedWolvesAttackTamedFoxes = false